print("Площадь окружности радиуса 2:", (lambda pi, radius: pi * (radius ** 2))(3.14, 2))
print()
print("Площадь прямоугольника 10*13:", (lambda x, y: x * y)(10, 13))
print()
print("Площадь трапеций для a=7, b=5, h=3:", (lambda a, b, h: (a + b) / 2 * h)(7, 5, 3))
