# Generated by Django 5.0.6 on 2024-06-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Russia_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.CharField(max_length=20),
        ),
    ]
